Lic
nuaa-rm/ros_learn pull request #16
Opened 2021-06-15 03:15 UTC by lccc233

2021-06-15 03:16 UTC, lccc233 commented
。

2021-06-16 12:12 UTC, bismarckkk requested changes
按注释修改

2021-06-16 12:12 UTC, bismarckkk commented on lic/client/package.xml
> +	<build_depend>message_generation</build_depend>
缩进不规范

2021-06-16 12:12 UTC, bismarckkk commented on lic/server/launch/node_launch.launch
> +    <node pkg="client" name="client0" type="client_node" output="screen" />
多开几个client

2021-06-20 02:46 UTC, bismarckkk requested changes
依然没有多开几个client进行测试，并且看代码里并不支持多个client发布到多个topic，群里提示有提到过这个可以利用anonymous选项完成

2021-06-20 02:46 UTC, bismarckkk commented on lic/server/src/start_server.cpp
>  ros::Subscriber name_info_sub[100];
建议使用list

2021-06-20 02:46 UTC, bismarckkk commented on lic/server/src/start_server.cpp
> +bool topicCallback(const client::topic_name::Request
应使用using减少参数类型长度

2021-06-20 02:46 UTC, bismarckkk commented on lic/server/src/start_server.cpp
> +    10, nameInfoCallback);
括号内换行应与括号对齐

2021-06-20 02:46 UTC, bismarckkk commented on lic/server/src/start_server.cpp
> +    n.subscribe<client::name>(aim_topic.c_str(),
非括号内换行应加入一个缩进

2021-06-20 03:06 UTC, closed without merging