Kevin tc
nuaa-rm/ros_learn pull request #37
Opened 2022-06-28 06:54 UTC by AbabalaT

Now using Ctrl + C to exit!

2022-06-28 09:51 UTC, bismarckkk requested changes
代码写的很不错，但有些地方ros做了处理不需要自己进行复杂的实现，建议改进

2022-06-28 09:51 UTC, bismarckkk commented on src/client/CMakeLists.txt
> +add_message_files(FILES current_time.msg)
不应该新增加一行指令，应直接解除原注释

2022-06-28 09:51 UTC, bismarckkk commented on src/client/CMakeLists.txt
> +add_executable(ros_learn_client src/client_main.cpp)
不应在此处自行添加，应解除原注释并进行修改

2022-06-28 09:51 UTC, bismarckkk commented on src/client/msg/current_time.msg
> +uint16 hour
建议使用ros原生的time类型

2022-06-28 09:51 UTC, bismarckkk commented on src/client/src/client_main.cpp
> +        logged = service_client.call(login_service_message);
建议添加请求失败处理  
例如service不存在等情况

2022-06-28 09:51 UTC, bismarckkk commented on src/client/src/client_main.cpp
> +    std::cin>>main_name;
node的名称是ros运行时生成的，也可由launch文件指定，请使用ros相关api获取

2022-06-28 09:51 UTC, bismarckkk commented on src/client/src/client_main.cpp
> +    while (ros::ok() && running_flag) {
掌握了信号量的运用，但此处并不适合信号量  
当执行ros::init()时，ros会自动注册SIGINT与SIGTERM信号量，并通过ros::ok()的返回值传递给主程序，当按下ctrl c，ros::ok()返回值变为假，即跳出while循环（若使用ros::spin()也将跳出spin函数），然后继续执行循环后代码，并启动超时守护线程，若循环后代码运行超时将直接结束主线程并抛出错误

2022-06-28 09:51 UTC, bismarckkk commented on src/server/src/server_main.cpp
> +ros::NodeHandle *server_node_handle_pointer = NULL;
ros的nodehandle是一种通过引用计数实现的单例模式，即不论何时何地，同一个进程中初始化的nh对象拥有同样的作用，所以只需要在回调函数里建立一个新的nh对象即可

2022-06-28 09:51 UTC, bismarckkk commented on src/server/src/server_main.cpp
> +ros::NodeHandle *server_node_handle_pointer = NULL;
参考：https://answers.ros.org/question/330706/i-m-trying-to-make-my-nodehandle-globalbelow-is-my-codebut-i-m-unable-to-listen-to-subscribed-topic/

2022-06-28 09:52 UTC, bismarckkk commented on src/client/src/client_main.cpp
> +    std::cin>>main_name;
参考：http://wiki.ros.org/roscpp/Overview/Names%20and%20Node%20Information

2022-06-28 09:53 UTC, bismarckkk commented on src/client/src/client_main.cpp
> +    while (ros::ok() && running_flag) {
参考：http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown

2022-07-09 12:20 UTC, AbabalaT commented on src/client/src/client_main.cpp
> +        logged = service_client.call(login_service_message);
service不存在会循环重复尝试

2022-07-09 12:57 UTC, closed without merging