Linshuo
nuaa-rm/ros_learn pull request #38
Opened 2022-07-02 11:20 UTC by Linshuo210607

[milestone] 完成阶段性目标

2022-07-05 12:04 UTC, bismarckkk requested changes
* 查看群内共性问题
* 查看群内共性问题
* 查看群内共性问题

2022-07-05 12:04 UTC, bismarckkk commented on Linshuo/client/src/client.cpp
> +    std::cin>>main_name;
查看群内共性问题

2022-07-05 12:04 UTC, bismarckkk commented on Linshuo/client/src/client.cpp
> +    signal(SIGINT, interrupt_handler);
查看群内共性问题

2022-07-05 12:04 UTC, bismarckkk commented on Linshuo/server/CMakeLists.txt
> + add_message_files(
只应该在一个node内生成消息类型，参考ros wiki教程

2022-07-05 12:04 UTC, bismarckkk commented on Linshuo/server/src/server.cpp
> +ros::NodeHandle *n_pointer = NULL;
查看群内共性问题

2022-07-05 12:04 UTC, bismarckkk commented on Linshuo/server/src/server.cpp
> +                each_subscriber.shutdown();
没有销毁对象

2022-07-06 09:35 UTC, bismarckkk reviewed
1. 文件目录错误，应新建自己的文件夹
2. 代码内不应保留代码注释，若该代码有必要在使用时切换应使用宏定义控制
3. 使用ros内置的中断解决方案可以简化代码，非必要不引入复杂功能

2022-07-08 01:20 UTC, bismarckkk commented on Linshuo/CMakeLists.txt
> +# toplevel CMakeLists.txt for a catkin workspace
top层cmake应是软连接产生而不是复制

2022-07-08 01:20 UTC, bismarckkk commented on Linshuo/client/CMakeLists.txt
> +add_executable(client src/client.cpp)
不应自行编写已存在的指令，应解除注释，自己写之后添加别的指令顺序就乱掉了

2022-07-08 01:20 UTC, bismarckkk commented on Linshuo/client/msg/time.msg
> +uint64 year
传输冗杂过大，应选用合适的数据范围及方法，如月份范围是1~12，应使用uint8。更进一步的，可以采用一个uint64传输时间戳，通过解析时间戳完成时间传递，也可直接使用ros的时间类型ros::Time

2022-07-08 01:20 UTC, bismarckkk commented on Linshuo/server/CMakeLists.txt
> +# generate_messages(
为啥你两个cmake都没有生成消息

2022-07-08 01:20 UTC, bismarckkk commented on Linshuo/server/src/server.cpp
> +        server_subscribers.pop_back();
pop_back是删除容器中最后一个对象，且没有放置于if循环内，这样直接把vector清空了，影响其余连接工作  
另：vector.clear()函数可以情况vector  
另：上次开会有提到过需要采用clike的循环写法而不是range-based，暴露出迭代器对象，采用erase方法删除特定下标对象

2022-07-08 08:01 UTC, Lin-qN commented on Linshuo/client/msg/time.msg
> +uint64 year
解析时间戳感觉好复杂

2022-07-08 08:03 UTC, Linshuo210607 commented on Linshuo/server/CMakeLists.txt
> +# generate_messages(
client里应该有吧，我可能自己写在下面了，我改改

2022-07-08 08:33 UTC, bismarckkk commented
有库的啊，cpp新引入的chrono，之前的ctime都可以，能直接打印成字符串

--------------原始邮件--------------
发件人："Linshuo210607 ***@***.***&gt;;
发送时间：2022年7月8日(星期五) 下午4:01
收件人："nuaa-rm/ros_learn" ***@***.***&gt;;
抄送："左清宇 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [nuaa-rm/ros_learn] Linshuo (PR #38)
-----------------------------------

 

 
@Linshuo210607 commented on this pull request.
 
 
In Linshuo/client/msg/time.msg:
 &gt; @@ -0,0 +1,9 @@ +uint64 year  
解析时间戳感觉好复杂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-07-08 09:04 UTC, closed without merging