Andy kong
nuaa-rm/ros_learn pull request #39
Opened 2022-07-04 07:49 UTC by AndyKong2020

2022-07-05 11:57 UTC, bismarckkk requested changes
1. 没有正确配置clion打开ros工程，请参考clion文档
2. 不应该将编程工具配置文件夹`.idea`上传至公共路径，应设置.gitignore或上传至自己的文件夹中
3. 请查看群内发过的共性问题，一共三条你全中

2022-07-05 11:57 UTC, bismarckkk commented on README.md
> +# 如何运行
应该在自己的文件夹下新建readme文件，而不是修改公共readme文件

2022-07-05 11:57 UTC, bismarckkk commented on konghao/client/CMakeLists.txt
> +add_dependencies(client ${PROJECT_NAME}_gencpp)
应该直接解除注释而不是重新编写指令

2022-07-05 11:57 UTC, bismarckkk commented on konghao/client/msg/time.msg
> +string sec
不应当用string类型传递时间，建议使用ros原生time类型

2022-07-05 11:57 UTC, bismarckkk commented on konghao/client/src/client.cpp
> +    signal(SIGINT, interrupt_handler);
参考汤陈pr中的评论和群里发过的共性问题，ros原生提供了程序结束处理，不应重复造轮子，可能会影响ros程序正常结束

2022-07-05 11:57 UTC, bismarckkk commented on konghao/client/src/client.cpp
> +    srv.request.node_name = name;
name不应该被输入，参考群里发过的共性问题，该值应该由ros生成或在launch中指定

2022-07-05 11:57 UTC, bismarckkk commented on konghao/server/msg/time.msg
> +string sec
重复的msg文件

2022-07-05 11:57 UTC, bismarckkk commented on konghao/server/CMakeLists.txt
> + add_message_files(
消息格式应该由一个节点统一提供，而不是每个节点都编写，请参考ros wiki教程

2022-07-05 11:57 UTC, bismarckkk commented on konghao/server/src/server.cpp
> +ros::NodeHandle *n_pointer = NULL;
不应该使用指针传递nh对象，请参考群内共性问题

2022-07-05 11:57 UTC, bismarckkk commented on konghao/server/src/server.cpp
> +                each_subscriber.shutdown();
没有从数组中销毁该对象，会导致内存异常增长

2022-07-09 08:26 UTC, bismarckkk reviewed
老问题快修啊😭

2022-07-09 08:26 UTC, bismarckkk commented on src/client/CMakeLists.txt
> + generate_messages(
阿巴阿巴，不要自己写，不要自己写，不要自己写，要解除注释，要解除注释，要解除注释

2022-07-09 08:26 UTC, bismarckkk commented on src/client/src/client.cpp
> +//#include <chrono>
没有用的代码请删除

2022-07-09 08:26 UTC, bismarckkk commented on src/server/CMakeLists.txt
> +   FILES
为啥两个cmake里都还有消息生成啊

2022-07-09 11:59 UTC, AndyKong2020 commented on src/client/CMakeLists.txt
> + generate_messages(
这段其实已经注释掉了，没删

2022-07-09 11:59 UTC, AndyKong2020 commented on src/server/CMakeLists.txt
> +   FILES
这段已经注释掉了，没删

2023-01-29 10:16 UTC, closed without merging